services:
  filestoring-db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: filestoring
    volumes:
      - filestoring_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d filestoring"]
      interval: 10s
      timeout: 5s
      retries: 5

  filestoring-service:
    build:
      context: .
      dockerfile: FileStoringService.Host/Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTIONSTRINGS__DB: Host=filestoring-db;Port=5432;Database=filestoring;Username=postgres;Password=postgres;
    depends_on:
      filestoring-db:
        condition: service_healthy

  fileanalysis-db:
    image: postgres:16
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fileanalysis
    volumes:
      - fileanalysis_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fileanalysis"]
      interval: 10s
      timeout: 5s
      retries: 5

  fileanalysis-service:
    build:
      context: .
      dockerfile: FileAnalysisService.Host/Dockerfile
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTIONSTRINGS__DB: Host=fileanalysis-db;Port=5432;Database=fileanalysis;Username=postgres;Password=postgres;
      FileStoringApi__BaseUrl: http://filestoring-service:8080
    depends_on:
      fileanalysis-db:
        condition: service_healthy
      filestoring-service:
        condition: service_started

  apigateway:
    build:
      context: .
      dockerfile: ApiGateway.Host/Dockerfile
    ports:
      - "5002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      FileStoringApi__BaseUrl: http://filestoring-service:8080
      FileAnalysisApi__BaseUrl: http://fileanalysis-service:8080

      Swagger__FileStoring: http://filestoring-service:8080/openapi/api.json
      Swagger__FileAnalysis: http://fileanalysis-service:8080/openapi/api.json
    depends_on:
      filestoring-service:
        condition: service_started
      fileanalysis-service:
        condition: service_started

volumes:
  filestoring_db_data:
  fileanalysis_db_data:
